name = "railwayfront"
compatibility_date = "2025-06-05"
compatibility_flags = ["nodejs_compat_v2"]

[vars]
API_BASE = "/"
APP_NAME = "RailwayFront"

# Output directory when using Nitro preset: 'cloudflare'
pages_build_output_dir = ".output/public"

[assets]
directory = ".output/public"