name = "railwayfront"
compatibility_date = "2025-06-05"
compatibility_flags = ["nodejs_compat"]

[vars]
API_BASE = "/"
APP_NAME = "RailwayFront"

# Required for wrangler pages deploy when using wrangler.toml
pages_build_output_dir = "dist"

[assets]
directory = "dist"